### PR TITLE
Noetic devel simulation remove redundant gains

### PR DESCRIPTION
**Pull request by rickstaa**
This pull request removes several redundant PID gains. See my comment in [pull request 126](https://github.com/frankaemika/franka_ros/pull/126) For a discussion of why I think they should be removed.

### CODE REVIEW

**Comment by rickstaa** [comment]
Closed temporary since something is wrong.

**Comment by rickstaa** [comment]
Re-opened as the bug is fixed now.

**Review by tahsinkose — CHANGES_REQUESTED** [review]
Please rebase and squeeze your fix commit into one. Also please remove "merge" commit in between.

EDIT: You should use `git rebase`.

**Comment by tahsinkose** [comment]
@rickstaa I'm closing this PR as it is duplicate of https://github.com/tahsinkose/panda_moveit_config/pull/4.

**Pull request closed without merging**
